# Gitpod configuration for Blankon Contracts
# Uses the existing Dockerfile for full compatibility with your devcontainer
image:
  file: Dockerfile

# VS Code extensions (Gitpod will install these automatically)
vscode:
  extensions:
    - rust-lang.rust-analyzer
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - ms-azuretools.vscode-docker

# Workspace tasks (run after workspace starts)
tasks:
  - name: Check tool versions
    init: |
      anchor --version
      solana --version
      rustc --version
      node --version
      yarn --version
      avm --version
  - name: Install Node dependencies
    command: yarn install
  - name: Build Rust project
    command: cargo build

# Ports to expose (add more if needed)
ports:
  - port: 8899
    onOpen: ignore
    description: Solana localnet (if used)

# Environment variables (add more as needed)
env:
  ANCHOR_WALLET: /workspace/blankon-contracts/secrets/solana-keypair.json

# VS Code settings (optional, can be extended)
vscode:
  settings:
    editor.formatOnSave: true
    editor.tabSize: 2
    editor.insertSpaces: true
    files.trimTrailingWhitespace: true
    files.insertFinalNewline: true
    files.eol: "\n"
    rust-analyzer.rustfmt.extraArgs: ["--config-path=rustfmt.toml"]
    rust-analyzer.check.command: "clippy"
    [typescript]:
      editor.tabSize: 2
      editor.insertSpaces: true
    [javascript]:
      editor.tabSize: 2
      editor.insertSpaces: true
    [toml]:
      editor.tabSize: 2
      editor.insertSpaces: true
    [shellscript]:
      editor.tabSize: 2
      editor.insertSpaces: true
    [markdown]:
      editor.tabSize: 2
      editor.wordWrap: on
      files.trimTrailingWhitespace: false
