[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
blankon_contracts = "99qG6bAkds5MpT37m61LFr8eJibvUGEu2GQ6TGxuwmda"

[programs.devnet]
blankon_contracts = "99qG6bAkds5MpT37m61LFr8eJibvUGEu2GQ6TGxuwmda"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./secrets/solana-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
