[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
blankon_contracts = "2ZV48S4LYwusvaahmKSSkkqcYFDPTPJHJhyHHMVLHuY4"

[programs.localnet]
blankon_contracts = "2ZV48S4LYwusvaahmKSSkkqcYFDPTPJHJhyHHMVLHuY4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./secrets/solana-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
